yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_details, name='post_details'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
import django.contrib.auth.views as auth
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        auth.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        auth.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        auth.PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        auth.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        auth.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        auth.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
CHARS_IN_STR = 15


class Group(models.Model):
    title = models.CharField('Название', max_length=200)
    slug = models.SlugField('Адрес', unique=True)
    description = models.TextField('Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'


class Post(models.Model):
    text = models.TextField('Текст', help_text='Введите текст поста')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Сообщество',
        help_text='Группа, к которой будет относиться пост'
    )

    def __str__(self):
        return self.text[:CHARS_IN_STR]

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User
from .forms import PostForm


POSTS_ON_SCREEN = 10


def add_paginator(request, object_list, per_page=POSTS_ON_SCREEN):
    paginator = Paginator(object_list, per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    post_list = Post.objects.select_related('author').all()
    context = {
        'page_obj': add_paginator(request, post_list)
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author').all()
    context = {
        'group': group,
        'page_obj': add_paginator(request, post_list),
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('author')
    context = {
        'author': author,
        'page_obj': add_paginator(request, post_list),
    }
    return render(request, 'posts/profile.html', context)


def post_details(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


def author_only(func):
    def check_author(request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if request.user.is_authenticated:
            if request.user == post.author:
                return func(request, post_id)
            return redirect('posts:post_details', post_id)
        return redirect('users:login')
    return check_author


@author_only
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_details', post_id)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base/base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
  <br>(Но это не точно)
</p>
<p>
  <a href="https://github.com/AVinAnd">github</a>
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base/base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base/base.html
<!DOCTYPE html>
<html lang="ru">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          (Y)_(=_=)_(Y)
        {% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/base/form_card.html
{% extends 'base/base.html' %}
{% block title %}title{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% block card_header %}Войти на сайт{% endblock %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post"
            {% block action %}
            {% endblock %}
          >
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            {% block button %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  {% block button_name %}Применить{% endblock %}
                </button>
              </div>
            {% endblock %}
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/base/form_result.html
{% extends 'base/base.html' %}
{% block title %}
  title
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% block card_header %}
            card-header
          {% endblock %}
        </div>
        <div class="card-body">
          {% block card_body %}
            card-body
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
           href="{% url 'about:author' %}">
            Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
           href="{% url 'about:tech' %}">
            Технологии
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}"
           href="{% url 'posts:post_create' %}">
            Новая запись
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}"
           href="{% url 'users:password_change' %}">
            Изменить пароль
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li>
        Пользователь: <a href="{% url 'posts:profile' user.username %}">{{ user.username }}</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}"
           href="{% url 'users:login' %}">
            Войти
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}"
           href="{% url 'users:signup' %}">
            Регистрация
        </a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endwith %}

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
        Предыдущая
      </a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
      <li class="page-item active">
        <span class="page-link">{{ i }}</span>
      </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">
        Следующая
      </a>
    </li>
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
        Последняя
      </a>
    </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/password_reset_confirm_right.html
{% extends 'base/form_card.html' %}
{% block title %}Новый пароль{% endblock %}
{% block card_header %}Введите новый пароль{% endblock %}
{% block button_name %}Назначить новый пароль{% endblock %}

yatube/templates/includes/password_reset_confirm_wrong.html
{% extends 'base/form_result.html' %}
{% block card_header %}Ошибка{% endblock %}
{% block card_body %}Ссылка сброса пароля содержит ошибку или устарела.{% endblock %}

yatube/templates/includes/post_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{post.pub_date|date:"d E Y" }}
    </li>
    <a href="{% url 'posts:profile' post.author %}">все посты автора</a>
  </ul>
  <p>{{ post.text|linebreaksbr }}</p>
</article>

yatube/templates/posts/create_post.html
{% extends 'base/form_card.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block card_header %}
  {% if is_edit %}
    Редактирование
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block action %}
  {% if is_edit %}
    action="{% url 'posts:post_edit' form.instance.id %}"
  {% else %}
    action="{% url 'posts:post_create' %}"
  {% endif %}
{% endblock %}
{% block button %}
  <div class="d-flex justify-content-end">
    <button type="submit" class="btn btn-primary">
      {% if is_edit %}
        Сохранить
      {% else %}
        Добавить
      {% endif %}
    </button>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base/base.html' %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    <a href="{% url 'posts:post_details' post.id %}">подробная информация</a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base/base.html' %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
    <a href="{% url 'posts:post_details' post.id %}">подробная информация</a>
    {% if post.group %} |
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы "{{ post.group.title }}"
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base/base.html' %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
        <li class="list-group-item">
          Группа: <a href="{% url 'posts:group_list' post.group.slug %}">
            {{ post.group.title }}</a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == request.user %}
        <a href="{% url 'posts:post_edit' post.id %}">редактировать</a>
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base/base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% for post in page_obj %}
    {% include 'includes/post_card.html' %}
      <a href="{% url 'posts:post_details' post.id %}">подробная информация</a>
    {% if post.group %} |
      <a href="{% url 'posts:group_list' post.group.slug %}">
        все записи группы "{{ post.group.title }}"
      </a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base/form_result.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block card_header%}Выход{% endblock %}
{% block card_body %}<p>Вы вышли из своей учётной записи. Ждём вас снова!</p>{% endblock %}

yatube/templates/users/login.html
{% extends "base/form_card.html" %}
{% block title %}Войти{% endblock %}
{% block card_header %}Войти на сайт{% endblock %}
{% block action %}
  {% if action_url %}
    action="{% url action_url %}"
  {% endif %}
{% endblock %}
{% block button %}
  <div class="col-md-6 offset-md-4">
    <button type="submit" class="btn btn-primary">Войти</button>
    <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">Забыли пароль?</a>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base/form_result.html' %}
{% block title %}Пароль изменен{% endblock %}
{% block card_header %}Изменить пароль{% endblock %}
{% block card_body %}Пароль изменен успешно{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base/form_card.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block card_header %}Изменить пароль{% endblock %}
{% block button_name %}Изменить пароль{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base/form_result.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block card_header %}Восстановление пароля завершено{% endblock %}
{% block card_body %}
  <p>Ваш пароль был сохранен. Используйте его для входа</p>
  <a href="../users/login.html">войти</a>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% if validlink %}
  {% include 'includes/password_reset_confirm_right.html' %}
{% else %}
  {% include 'includes/password_reset_confirm_wrong.html' %}
{% endif %}

yatube/templates/users/password_reset_done.html
{% extends 'base/form_result.html' %}
{% block title %}Сброс пароля прошел успешно{% endblock %}
{% block card_header %}Отправлено письмо{% endblock %}
{% block card_body %}
  Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base/form_card.html' %}
{% block title %}Сброс пароля{% endblock %}
{% block card_header %}
  Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
{% endblock %}
{% block button_name %}Сбросить пароль{% endblock %}

yatube/templates/users/signup.html
{% extends "base/form_card.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block card_header %}Зарегистрироваться{% endblock %}
{% block action %}action="{% url 'users:signup' %}"{% endblock %}
{% block button_name %}Зарегистрироваться{% endblock %}